# Generated by Django 5.2.11 on 2026-02-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_new_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Новое здание'),
        ),
    ]
