# Generated by Django 5.2.11 on 2026-02-03 19:13

from django.db import migrations

def mark_new_buildings(apps, schema_editor):
    flat = apps.get_model('property', 'Flat')
    flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    flat.objects.filter(construction_year__lt=2015).update(new_building=False)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(mark_new_buildings)
    ]
