# Generated by Django 5.2.11 on 2026-02-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_liked_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owners_phonenumber',
            new_name='owners_phone_number',
        ),
        migrations.AddField(
            model_name='flat',
            name='owner_pure_phone',
            field=models.CharField(default=1, max_length=20, verbose_name='Нормализованный номер владельца'),
            preserve_default=False,
        ),
    ]
