# Generated by Django 5.2.11 on 2026-02-04 18:03

from django.db import migrations


def move_owner_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all().iterator():
        owner_obj, _ = Owner.objects.get_or_create(
            name=flat.owner,
            defaults={
                'phone_number': flat.owners_phone_number,
                'pure_phone': flat.owner_pure_phone,
            }
        )
        owner_obj.flat.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_owner'),
    ]

    operations = [
        migrations.RunPython(move_owner_to_owner)
    ]
